<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Страничка админа</title>
    <meta name="description" content="Страничка админа">
    <style>
        a {
            border: 2px solid black;
            display: inline-block;
            padding: 10px 20px;
            margin: 5px;
            background-color: white;
            color: black;
            text-decoration: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
        }

    </style>
</head>
<body>
</body>
<a href='admin/computers'>Компьютеры</a>
<a href='admin/playstations'>Плейстейшены</a>
<br>
<a href='admin/gamingPlaces'>Игровые места</a>
<a href='admin/computerPlaces'>Компьютерные места</a>
<a href='admin/playStationPlaces'>Плейстейшн места</a>
<br>
<a href='admin/computerAssignments'>Назначение компьютера</a>
<a href='admin/playStationAssignments'>Назначение плейстейшна</a>
<br>
<a href='admin/reservations'>Бронирования</a>
<a href='admin/users'>Пользователи</a>
</html>